apiVersion: v1
kind: Secret
metadata:
  name: csr-db-backup
type: Opaque
data:
  aws_secret_access_key_id: FillMe!
  aws_secret_access_key: FillMe!
  database_user: FillMe!
  database_password: FillMe!
# slack_webhook_url: <Your Slack WebHook URL>