apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: csr-db-backup
spec:
  schedule: "59 23 * * 5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: csr-db-backup
            image: pitscher/csr-database-backup:1.0
            imagePullPolicy: Always
            env:
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: csr-db-backup
                    key: aws_secret_access_key_id
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                   name: csr-db-backup
                   key: aws_secret_access_key
              - name: AWS_DEFAULT_REGION
                value: "fra1"
              - name: AWS_BUCKET_NAME
                value: "csr-backup"
              - name: AWS_BUCKET_BACKUP_PATH
                value: "/csr-db-backup"
              - name: TARGET_DATABASE_HOST
                value: "FillMe!"
              - name: TARGET_DATABASE_PORT
                value: "3306"
              - name: TARGET_DATABASE_NAMES
                value: "FillMe!"
              - name: TARGET_DATABASE_USER
                valueFrom:
                  secretKeyRef:
                    name: csr-db-backup
                    key: database_user
              - name: TARGET_DATABASE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: csr-db-backup
                    key: database_password
              - name: BACKUP_TIMESTAMP
                value: "-%d-%m-%Y"
              - name: SLACK_ENABLED
                value: "false"
#             - name: SLACK_CHANNEL
#               value: "#chatops"
#             - name: SLACK_WEBHOOK_URL
#               valueFrom:
#                  secretKeyRef:
#                    name: my-database-backup
#                    key: slack_webhook_url
          restartPolicy: Never