apiVersion: v1
kind: Service
metadata:
  name: csr-db-svc
  namespace: default
  labels:
    project: csr
spec:
  type: ClusterIP
  selector:
    app: csr-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      name: csr-db-svc