apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csr-db-pvc
  namespace: default
  labels:
    project: csr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: do-block-storage