apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: 3dstudis-net-cluster-issuer
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: mail@hn-goering.de
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: 3dstudis-net
    # Enable the HTTP-01 challenge provider
    http01: {}